from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrichments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrichment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("Other", "Other"),
                    ("Jira", "Jira"),
                    ("ServiceNow", "ServiceNow"),
                    ("PagerDuty", "PagerDuty"),
                    ("Slack", "Slack"),
                    ("ASP", "ASP"),
                    ("Internal", "Internal"),
                    ("Internal CMDB", "Internal CMDB"),
                    ("Internal Knowledge Base", "Internal Knowledge Base"),
                    ("Internal SIRP", "Internal SIRP"),
                    ("Mock", "Mock"),
                    ("MockTIProvider", "MockTIProvider"),
                    ("AlienVaultOTX", "AlienVaultOTX"),
                    ("VirusTotal", "VirusTotal"),
                    ("AbuseIPDB", "AbuseIPDB"),
                    ("urlscan.io", "urlscan.io"),
                    ("Shodan", "Shodan"),
                    ("Censys", "Censys"),
                    ("GreyNoise", "GreyNoise"),
                    ("MISP", "MISP"),
                    ("OpenCTI", "OpenCTI"),
                    ("Recorded Future", "Recorded Future"),
                    ("Mandiant", "Mandiant"),
                    ("CrowdStrike Intelligence", "CrowdStrike Intelligence"),
                    ("Microsoft Defender Threat Intelligence", "Microsoft Defender Threat Intelligence"),
                    ("IBM X-Force", "IBM X-Force"),
                    ("Cisco Talos", "Cisco Talos"),
                    ("Palo Alto Unit 42", "Palo Alto Unit 42"),
                    ("FortiGuard", "FortiGuard"),
                    ("Check Point ThreatCloud", "Check Point ThreatCloud"),
                    ("Kaspersky", "Kaspersky"),
                    ("ESET", "ESET"),
                    ("Trend Micro", "Trend Micro"),
                    ("Proofpoint", "Proofpoint"),
                    ("Flashpoint", "Flashpoint"),
                    ("URLhaus", "URLhaus"),
                    ("NVD", "NVD"),
                    ("ZeroFox", "ZeroFox"),
                    ("Darktrace", "Darktrace"),
                    ("Custom YARA", "Custom YARA"),
                    ("MaxMind", "MaxMind"),
                    ("IPinfo", "IPinfo"),
                    ("IP2Location", "IP2Location"),
                    ("WhoisXML API", "WhoisXML API"),
                    ("SecurityTrails", "SecurityTrails"),
                    ("DomainTools", "DomainTools"),
                    ("Google DNS", "Google DNS"),
                    ("Cloudflare DNS", "Cloudflare DNS"),
                    ("Quad9", "Quad9"),
                    ("Splunk", "Splunk"),
                    ("Elastic", "Elastic"),
                    ("Microsoft Sentinel", "Microsoft Sentinel"),
                    ("IBM QRadar", "IBM QRadar"),
                    ("Google Chronicle", "Google Chronicle"),
                    ("Sumo Logic", "Sumo Logic"),
                    ("LogRhythm", "LogRhythm"),
                    ("ArcSight", "ArcSight"),
                    ("Microsoft Defender XDR", "Microsoft Defender XDR"),
                    ("Microsoft Defender for Endpoint", "Microsoft Defender for Endpoint"),
                    ("CrowdStrike", "CrowdStrike"),
                    ("CrowdStrike Falcon", "CrowdStrike Falcon"),
                    ("SentinelOne", "SentinelOne"),
                    ("Palo Alto Cortex XDR", "Palo Alto Cortex XDR"),
                    ("Trellix", "Trellix"),
                    ("Carbon Black", "Carbon Black"),
                    ("VMware Carbon Black", "VMware Carbon Black"),
                    ("Cybereason", "Cybereason"),
                    ("Sophos", "Sophos"),
                    ("Trend Micro Vision One", "Trend Micro Vision One"),
                    ("Microsoft Entra ID", "Microsoft Entra ID"),
                    ("Microsoft Graph", "Microsoft Graph"),
                    ("Okta", "Okta"),
                    ("Ping Identity", "Ping Identity"),
                    ("Duo", "Duo"),
                    ("CyberArk", "CyberArk"),
                    ("SailPoint", "SailPoint"),
                    ("AWS IAM", "AWS IAM"),
                    ("Azure IAM", "Azure IAM"),
                    ("Google Cloud IAM", "Google Cloud IAM"),
                    ("Kubernetes API", "Kubernetes API"),
                    ("AWS", "AWS"),
                    ("AWS CloudTrail", "AWS CloudTrail"),
                    ("AWS GuardDuty", "AWS GuardDuty"),
                    ("AWS Security Hub", "AWS Security Hub"),
                    ("AWS Inspector", "AWS Inspector"),
                    ("Azure", "Azure"),
                    ("Azure Activity Log", "Azure Activity Log"),
                    ("Microsoft Defender for Cloud", "Microsoft Defender for Cloud"),
                    ("Google Cloud", "Google Cloud"),
                    ("Google Security Command Center", "Google Security Command Center"),
                    ("GCP Audit Log", "GCP Audit Log"),
                    ("Oracle Cloud", "Oracle Cloud"),
                    ("Alibaba Cloud", "Alibaba Cloud"),
                    ("Tencent Cloud", "Tencent Cloud"),
                    ("Palo Alto", "Palo Alto"),
                    ("Fortinet", "Fortinet"),
                    ("Check Point", "Check Point"),
                    ("Cisco", "Cisco"),
                    ("Juniper", "Juniper"),
                    ("Zscaler", "Zscaler"),
                    ("Cloudflare", "Cloudflare"),
                    ("Akamai", "Akamai"),
                    ("F5", "F5"),
                    ("Blue Coat", "Blue Coat"),
                    ("Forcepoint", "Forcepoint"),
                    ("Proofpoint Email Security", "Proofpoint Email Security"),
                    ("Mimecast", "Mimecast"),
                    ("Qualys", "Qualys"),
                    ("Tenable", "Tenable"),
                    ("Rapid7", "Rapid7"),
                    ("Nessus", "Nessus"),
                    ("Nexpose", "Nexpose"),
                    ("Wiz", "Wiz"),
                    ("Orca Security", "Orca Security"),
                    ("Prisma Cloud", "Prisma Cloud"),
                    ("Lacework", "Lacework"),
                    ("Cuckoo", "Cuckoo"),
                    ("Joe Sandbox", "Joe Sandbox"),
                    ("ANY.RUN", "ANY.RUN"),
                    ("Hybrid Analysis", "Hybrid Analysis"),
                    ("Triage", "Triage"),
                    ("CAPE", "CAPE"),
                    ("MANUAL", "MANUAL"),
                ],
                default="Other",
                help_text="Enrichment provider",
                max_length=50,
            ),
        ),
    ]
