# Generated by Django 6.0.6 on 2026-06-28 04:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_id', models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Record ID e.g. alert_000001, auto-generated, no manual input needed', max_length=32, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text='Alert title', max_length=500)),
                ('severity', models.CharField(choices=[('Unknown', 'Unknown'), ('Informational', 'Informational'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Unknown', help_text='Source-defined severity', max_length=20)),
                ('confidence', models.CharField(choices=[('Unknown', 'Unknown'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Unknown', help_text='True-positive confidence', max_length=20)),
                ('impact', models.CharField(choices=[('Unknown', 'Unknown'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Unknown', help_text='Potential impact', max_length=20)),
                ('disposition', models.CharField(choices=[('Unknown', 'Unknown'), ('Allowed', 'Allowed'), ('Blocked', 'Blocked'), ('Quarantined', 'Quarantined'), ('Isolated', 'Isolated'), ('Deleted', 'Deleted'), ('Dropped', 'Dropped'), ('Custom Action', 'Custom Action'), ('Approved', 'Approved'), ('Restored', 'Restored'), ('Exonerated', 'Exonerated'), ('Corrected', 'Corrected'), ('Partially Corrected', 'Partially Corrected'), ('Uncorrected', 'Uncorrected'), ('Delayed', 'Delayed'), ('Detected', 'Detected'), ('No Action', 'No Action'), ('Logged', 'Logged'), ('Tagged', 'Tagged'), ('Alert', 'Alert'), ('Count', 'Count'), ('Reset', 'Reset'), ('Captcha', 'Captcha'), ('Challenge', 'Challenge'), ('Access Revoked', 'Access Revoked'), ('Rejected', 'Rejected'), ('Unauthorized', 'Unauthorized'), ('Error', 'Error'), ('Other', 'Other')], default='Unknown', help_text='Source disposition', max_length=20)),
                ('action', models.CharField(choices=[('Unknown', 'Unknown'), ('Allowed', 'Allowed'), ('Denied', 'Denied'), ('Observed', 'Observed'), ('Modified', 'Modified'), ('Other', 'Other')], default='Unknown', help_text='Observed action', max_length=20)),
                ('labels', models.JSONField(blank=True, default=list, help_text='Alert labels')),
                ('desc', models.TextField(blank=True, default='', help_text='Alert description')),
                ('first_seen_time', models.DateTimeField(blank=True, help_text='First observed time', null=True)),
                ('last_seen_time', models.DateTimeField(blank=True, help_text='Last observed time', null=True)),
                ('rule_id', models.CharField(blank=True, default='', help_text='SIEM rule ID', max_length=255)),
                ('rule_name', models.CharField(blank=True, default='', help_text='SIEM rule name', max_length=255)),
                ('correlation_uid', models.CharField(blank=True, db_index=True, default='', help_text='Case correlation ID, alerts with the same correlation_uid are linked to the same event', max_length=255)),
                ('src_url', models.URLField(blank=True, default='', help_text='Source alert URL', max_length=500)),
                ('source_uid', models.CharField(blank=True, db_index=True, default='', help_text='Source product ID, can be used to locate the unique alert in the source system', max_length=255)),
                ('data_sources', models.JSONField(blank=True, default=list, help_text='Underlying data sources')),
                ('analytic_name', models.CharField(blank=True, default='', help_text='Analytic engine name', max_length=255)),
                ('analytic_type', models.CharField(choices=[('Unknown', 'Unknown'), ('Rule', 'Rule'), ('Behavioral', 'Behavioral'), ('Statistical', 'Statistical'), ('Learning (ML/DL)', 'Learning (ML/DL)'), ('Fingerprinting', 'Fingerprinting'), ('Tagging', 'Tagging'), ('Keyword Match', 'Keyword Match'), ('Regular Expressions', 'Regular Expressions'), ('Exact Data Match', 'Exact Data Match'), ('Partial Data Match', 'Partial Data Match'), ('Indexed Data Match', 'Indexed Data Match'), ('Other', 'Other')], default='Unknown', help_text='Analytic engine type', max_length=30)),
                ('analytic_state', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Active', 'Active'), ('Suppressed', 'Suppressed'), ('Experimental', 'Experimental'), ('Other', 'Other')], default='', help_text='Analytic rule state', max_length=20)),
                ('analytic_desc', models.TextField(blank=True, default='', help_text='Analytic rule description')),
                ('tactic', models.CharField(blank=True, choices=[('Reconnaissance', 'Reconnaissance'), ('Resource Development', 'Resource Development'), ('Initial Access', 'Initial Access'), ('Execution', 'Execution'), ('Persistence', 'Persistence'), ('Privilege Escalation', 'Privilege Escalation'), ('Defense Evasion', 'Defense Evasion'), ('Credential Access', 'Credential Access'), ('Discovery', 'Discovery'), ('Lateral Movement', 'Lateral Movement'), ('Collection', 'Collection'), ('Command and Control', 'Command and Control'), ('Exfiltration', 'Exfiltration'), ('Impact', 'Impact')], default='', help_text='Mapped MITRE tactic', max_length=100)),
                ('technique', models.CharField(blank=True, default='', help_text='Mapped MITRE technique', max_length=100)),
                ('sub_technique', models.CharField(blank=True, default='', help_text='Mapped MITRE sub-technique', max_length=100)),
                ('mitigation', models.TextField(blank=True, default='', help_text='Suggested mitigation')),
                ('product_category', models.CharField(blank=True, choices=[('DLP', 'DLP'), ('Email', 'Email'), ('OT', 'OT'), ('Proxy', 'Proxy'), ('UEBA', 'UEBA'), ('ThreatIntelligence', 'ThreatIntelligence'), ('IAM', 'IAM'), ('EDR', 'EDR'), ('NDR', 'NDR'), ('Cloud', 'Cloud'), ('SIEM', 'SIEM'), ('WAF', 'WAF'), ('Other', 'Other')], default='', help_text='Source product category', max_length=30)),
                ('product_vendor', models.CharField(blank=True, default='', help_text='Source vendor', max_length=255)),
                ('product_name', models.CharField(blank=True, default='', help_text='Source product name', max_length=255)),
                ('product_feature', models.CharField(blank=True, default='', help_text='Source product feature', max_length=255)),
                ('policy_name', models.CharField(blank=True, default='', help_text='Trigger policy name', max_length=255)),
                ('policy_type', models.CharField(blank=True, choices=[('Identity Policy', 'Identity Policy'), ('Resource Policy', 'Resource Policy'), ('Service Control Policy', 'Service Control Policy'), ('Access Control Policy', 'Access Control Policy'), ('Other', 'Other')], default='', help_text='Trigger policy type', max_length=30)),
                ('policy_desc', models.TextField(blank=True, default='', help_text='Trigger policy description')),
                ('risk_level', models.CharField(blank=True, choices=[('Info', 'Info'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical'), ('Other', 'Other')], default='', help_text='Assessed risk level', max_length=20)),
                ('status', models.CharField(choices=[('Unknown', 'Unknown'), ('New', 'New'), ('In Progress', 'In Progress'), ('Suppressed', 'Suppressed'), ('Resolved', 'Resolved'), ('Archived', 'Archived'), ('Deleted', 'Deleted'), ('Other', 'Other')], default='New', help_text='Alert handling status', max_length=20)),
                ('status_detail', models.TextField(blank=True, default='', help_text='Handling status details')),
                ('remediation', models.TextField(blank=True, default='', help_text='Remediation advice or record')),
                ('unmapped', models.JSONField(blank=True, default=dict, help_text='Raw unmapped fields, JSON Format')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Raw alert log JSON')),
                ('artifacts', models.ManyToManyField(blank=True, help_text='Extracted artifacts', related_name='alerts', to='artifacts.artifact')),
                ('case', models.ForeignKey(help_text='Linked case id, reverse association, auto-linked, no manual setting needed', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cases.case')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
