# Generated by Django 6.0.6 on 2026-06-28 04:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_id', models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Record ID e.g. knowledge_000001', max_length=32, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text='Knowledge title', max_length=500)),
                ('body', models.TextField(blank=True, default='', help_text='Knowledge content')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Knowledge expiration time; empty means permanently valid', null=True)),
                ('source', models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Case', 'Case')], default='', help_text='Knowledge source', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Knowledge tags')),
                ('case', models.OneToOneField(blank=True, help_text='Case this Knowledge was extracted from; empty for manual Knowledge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_knowledge', to='cases.case')),
            ],
            options={
                'db_table': 'knowledge',
                'ordering': ['-created_at'],
            },
        ),
    ]
